package Utils;

public enum InvalidacoesCandidato {
    CPF_ABAIXO_TAMANHO_MINIMO,
    CPF_ACIMA_TAMANHO_MAXIMO,
    CPF_EM_BRANCO,
    CPF_NULO,
    TELEFONE_ABAIXO_TAMANHO_MINIMO,
    TELEFONE_ACIMA_TAMANHO_MAXIMO,
    TELEFONE_EM_BRANCO,
    TELEFONE_NULO
}
